### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by hanjo8813** [hanjo8813/SpringBoot-Board#1]
## 설정

- [x] Spring Boot 프로젝트 init
- [x] RDS에서 DB 생성 + Spring 에 연동
- [x] 테스트 UI 구현
- [x] Docker로 실행 테스트
- [x] EC2에 Docker 컨테이너 띄워보기 -> https://github.com/hanjo8813/SpringBoot-Board/issues/2
   - [ ]  초기 설정 shell 파일 작성
- [x] 간단한 React 페이지로 api 호출
- [x] React 빌드 후 S3 + Cloudfront로 올리기 -> https://github.com/hanjo8813/SpringBoot-Board/issues/3
- [x] nginx + cerbot 으로 EC2에 https 적용 -> https://github.com/hanjo8813/SpringBoot-Board/issues/10
- [ ] Jekins로 CI/CD 설정

## 기능 구현

- [x] 도메인 엔티티 구현
- [x] 회원 관련 기능
   - [x] 회원가입 기능
   - [x] 로그인 기능
   - [x] 내 정보 조회
   - [x] 회원탈퇴 기능
- [x] 게시판 기능
   - [x] 게시글 작성
   - [x] 내 게시글 조회
   - [x] 게시글 단건 조회
   - [x] 게시글 페이징 조회
   - [x] 게시글 수정
   - [x] 게시글 삭제
 - [x] 검증 및 Exception 처리 
    - [x] Bean Validation 적용
    - [x] Exception Handler 적용
- [x] 테스트코드 작성
   - [x] Service
   - [x] Controller
   - [x] Rest Docs 생성
   - [x] Rest Docs 화면 출력

## 예외처리
> insert / update 될때

- 올바르지 않은 email 형식 
- 회원가입시 빈값
- 게시물 등록시 빈값
- 게시물 수정시 빈값

**Comment by hanjo8813** [comment]
## 궁금한점

- 기존 테이블이 설계되어 있을때 jpa 엔티티는 어떻게 설계?
-
